version: '3.1'
services:
  redis-stack:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - redisData:/data  # `REDIS_DATA_DIR` in .env.dev

volumes:
  redisData:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chengjia/Dev/volumes/redisData
