version: '3.1'
services:
  api: # API Service
    build: # Provide dockerfile info for image build
      context: ./  # Dockerfile's relative path to current YAML
      dockerfile: Dockerfile.dev.mac
    command: python ./main.py --host 0.0.0.0 --port 5000 --debug
    volumes:
      - apiStorage:/usr/image_search/storage  # `STORAGE_ROOT` in .env.dev
      - apiLogs:/usr/image_search/logs  # `LOGGING_ROOT` in .env.dev
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack-server:7.2.0-v6
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PWD} --dir ${REDIS_DATA_DIR} --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so"
    environment:
      # Persist after 1hr if 1 write, after 5min if 100 writes, after 60 sec if 10000 writes
      - REDIS_ARGS=--save 3600 1 --save 300 100 --save 60 10000
    ports:
      - 6379:6379
    volumes:
      - redisData:${REDIS_DATA_DIR}
    env_file:
      - .env.dev

volumes:
  redisData:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/chengjia/Dev/volumes/redisData  # For test on Mac
  apiStorage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/chengjia/Dev/volumes/apiStorage  # For test on Mac
  apiLogs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/chengjia/Dev/volumes/apiLogs  # For test on Mac
